### ISSUE TITLE
Getting a java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by chathurawidanage** [jchambers/jeospatial#9]
I am getting below error when trying to handle an index of size 100000000. 

Sample program

```java
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.eatthepath.jeospatial.VPTreeGeospatialIndex;
import com.eatthepath.jeospatial.GeospatialPoint;

public class GeoIndexTest {

    public static void main(String[] args) {
        List<GeospatialPoint> points = new ArrayList<>();

        final Random r = new Random();

        long t1 = System.currentTimeMillis();
        for (int i = 0; i < 100000000; i++) {

            points.add(new GeospatialPoint() {

                @Override
                public double getLatitude() {
                    return (r.nextDouble() * -180.0) + 90.0;
                }

                @Override
                public double getLongitude() {
                    return (r.nextDouble() * -360.0) + 180.0;
                }

            });
        }
        long t2 = System.currentTimeMillis();
        System.out.println("Inserted in " + (t2 - t1));

        points.add(new GeospatialPoint(){

			@Override
			public double getLatitude() {
				// TODO Auto-generated method stub
				return 39.165325d;
			}

			@Override
			public double getLongitude() {
				// TODO Auto-generated method stub
				return -86.5263857d;
			}
            
        });

        VPTreeGeospatialIndex vpti = new VPTreeGeospatialIndex(points);

        // indiana
        List allPointsInBoundingBox = vpti.getAllPointsInBoundingBox(37.96, -87.54d, 41.76, -84.81d);
        System.out.println("Results : " + allPointsInBoundingBox.size());
        long t3 = System.currentTimeMillis();
        System.out.println("Searched in " + (t3 - t2));
    }
}
```

Output
```bash
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -65467727 out of bounds for length 100000001
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:426)
        at com.eatthepath.jvptree.util.SamplingMedianDistanceThresholdSelectionStrategy.getSampledPoints(SamplingMedianDistanceThresholdSelectionStrategy.java:61)
        at com.eatthepath.jvptree.util.SamplingMedianDistanceThresholdSelectionStrategy.selectThreshold(SamplingMedianDistanceThresholdSelectionStrategy.java:43)
        at com.eatthepath.jvptree.VPTreeNode.anneal(VPTreeNode.java:88)
        at com.eatthepath.jvptree.VPTreeNode.<init>(VPTreeNode.java:62)
        at com.eatthepath.jvptree.VPTree.<init>(VPTree.java:129)
        at com.eatthepath.jvptree.VPTree.<init>(VPTree.java:70)
        at com.eatthepath.jeospatial.VPTreeGeospatialIndex.<init>(VPTreeGeospatialIndex.java:24)
        at edu.iu.iuni.moe.GeoIndexTest.main(GeoIndexTest.java:53)
```

**Comment by jchambers** [comment]
This was fixed in https://github.com/jchambers/jvptree/pull/10.
